spring.application.name=payment-service

server.port=${SERVER_PORT:8085}

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://discovery:8010/eureka}

eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=${EUREKA_REGISTRY_FETCH_INTERVAL_SECONDS:5}
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

spring.rabbitmq.host=rabbitmq

spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:false}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/payment_db}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
