server:
  port: ${SERVER_PORT:8082}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery:8010/eureka}
    registry-fetch-interval-seconds: ${EUREKA_REGISTRY_FETCH_INTERVAL_SECONDS:5}
  instance:
    prefer-ip-address: true


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      cache:
        enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - '*'
            allowed-origin-patterns:
              - '*'
            allowed-headers:
              - '*'
            exposed-headers:
              - '*'
            allowed-methods:
              - '*'
          '/**':
            allowed-origin-patterns:
              - '*'
            allowed-origins:
              - '*'
            allowed-headers:
              - '*'
            allowed-methods:
              - '*'
        add-to-simple-url-handler-mapping: true
      routes:
        - id: travel-core-hotels
          uri: lb://travel-core-service
          predicates:
            - Path=/hotels/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: travel-core-transports
          uri: lb://travel-core-service
          predicates:
            - Path=/transports/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/community/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/reservations/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods: '*'
              allowedHeaders: '*'
        - id: ai-arrange-websocket
          uri: lb:ws://ai-arrange-service
          predicates:
            - Path=/ai-arrange/ws/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: ai-arrange-service
          uri: lb://ai-arrange-service
          predicates:
            - Path=/ai-arrange/**
          filters:
            - RemoveRequestHeader=Cookie
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
