spring.application.name=reservation-service

server.port=0

eureka.client.service-url.defaultZone=http://discovery:8010/eureka

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

spring.rabbitmq.host=rabbitmq

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/data/reservation-db;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
