# version: "3.9"
name: rsww_184249

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
      - ./logs/rabbitmq:/var/log/rabbitmq
    networks:
      - backend

  discovery:
    hostname: discovery
    build: ./discovery-service
    ports:
      - "8010:8010"
    volumes:
      - ./logs/discovery:/logs
    depends_on:
      - rabbitmq
    networks:
      - backend

  gateway:
    build: ./api-gateway
    ports:
      - "8082:8082"
    volumes:
      - ./logs/gateway:/logs
    depends_on:
      - rabbitmq
      - discovery
    networks:
      - backend

  hotel:
    build: ./hotel-service
    volumes:
      - ./logs/hotel:/logs
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  payment:
    build: ./payment-service
    volumes:
      - ./logs/payment:/logs
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  reservation:
    build: ./reservation-service
    volumes:
      - ./logs/reservation:/logs
      - ./data/reservation-service:/data
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  transport:
    build: ./transport-service
    volumes:
      - ./logs/transport:/logs
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

  user:
    build: ./user-service
    volumes:
      - ./logs/user:/logs
      - ./data/user-service:/data
    depends_on:
      - rabbitmq
      - discovery
      - gateway
    networks:
      - backend

networks:
  backend:

