spring.application.name=user-service

server.port=0

eureka.client.service-url.defaultZone=http://discovery:8010/eureka

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

spring.rabbitmq.host=rabbitmq

# H2 file database - development persistence
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/data/user-db;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update


# Postgres database on Docker - production
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://userdb:5432/users
#spring.datasource.username=admin
#spring.datasource.password=admin
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.default_schema = public

