spring.application.name=discovery-service

eureka.instance.hostname=discovery
server.port=${SERVER_PORT:8010}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.maxThreadsForPeerReplication=0
eureka.server.enable-self-preservation=${EUREKA_SERVER_ENABLE_SELF_PRESERVATION:false}
eureka.server.eviction-interval-timer-in-ms=${EUREKA_SERVER_EVICTION_INTERVAL_TIMER_MS:5000}
